parameters:
    page.services.helpers_class: BardisCMS\PageBundle\Services\Helpers
    page.services.show_error_page_class: BardisCMS\PageBundle\Services\ShowErrorPage
    page.listener.response_listener_class: BardisCMS\PageBundle\Listener\ResponseListener
    page.services.ajax_detection_class: BardisCMS\PageBundle\Services\AjaxDetection
    page.services.http_cache_headers_handler_class: BardisCMS\PageBundle\Services\HttpCacheHeadersHandler

services:
    bardiscms_page.services.helpers:
        class: %page.services.helpers_class%
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

        kernel.listener.response_listener:
            class: %page.listener.response_listener_class%
            tags:
               - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    bardiscms_page.services.show_error_page:
        class: %page.services.show_error_page_class%
        arguments: ["@doctrine.orm.entity_manager", "@service_container",]

    bardiscms_page.services.ajax_detection:
        class: %page.services.ajax_detection_class%
        scope: request
        arguments: ["@request_stack"]

    bardiscms_page.services.http_cache_headers_handler:
        class: %page.services.http_cache_headers_handler_class%
