parameters:
    skeleton.services.helpers_class: BardisCMS\SkeletonBundle\Services\Helpers

services:
    bardiscms_skeleton.services.helpers:
        class: %skeleton.services.helpers_class%
        arguments: ["@doctrine.orm.entity_manager"]



